### ISSUE TITLE
Replication of wav2vec2 with RFP

### ISSUE THREAD

**Issue by Usanter** [AmirAbaskohi/Automatic-Speech-recognition-for-Speech-Assessment-of-Persian-Preschool-Children#1]
First of all, congratulation on the paper and the scores you achieved!

We would like to replicate the Wav2vec2.0 training using RFP (ideally using google colab as mentioned in the paper). What are the steps to follow? 

Best regards,
Thomas

**Comment by AmirAbaskohi** [comment]
Thanks
The notebook that I used is based on my information and there are some manual steps in it. I will add a complete notebook for this model as soon as possible. I will announce you.
For now, you can check files in the bin directory about how to run them.

Sincerely,
Amirhossein

**Comment by Usanter** [comment]
Hey, thanks for the quick answer. 
Looking forward to run this notebook!
Where can I find the bin directory? When I did a search over the repository for bin, it only show it in .gitignore. Could it be possible that you didn't upload it?

**Comment by AmirAbaskohi** [comment]
Yes, that was my mistake. Thank you for mentioning that. Now it is available [here](https://github.com/AmirAbaskohi/Automatic-Speech-recognition-for-Speech-Assessment-of-Persian-Preschool-Children/tree/main/Models/Wav2Vec%202.0/bin).

**Comment by AmirAbaskohi** [comment]
I have added the notebook as well.
